import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    height: 280,
    width: '100%',
  },
  imageHeader: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerContent: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 10,
  },
  headerSubtitle: {
    fontSize: 18,
    color: '#FFFFFF',
    marginTop: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  section: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 16,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  card: {
    backgroundColor: '#3B3944',
    borderRadius: 20,
    padding: 25,
    maxWidth: 450,
    width: '100%',
    marginTop: 10,
  },
  cardText: {
    color: '#FFFFFF',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 24,
  },
  formulaMainCard: {
    backgroundColor: '#3B3944',
    borderRadius: 15,
    padding: 20,
    width: '100%',
    maxWidth: 450,
    marginBottom: 20,
    alignItems: 'center',
  },
  formulaMainText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  explanationGrid: {
    width: '100%',
    maxWidth: 450,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  explanationCard: {
    backgroundColor: '#3B3944',
    borderRadius: 15,
    padding: 18,
    width: '48%',
    minHeight: 100,
    justifyContent: 'center',
    marginBottom: 15,
  },
  explanationText: {
    color: '#FFFFFF',
    fontSize: 13,
    textAlign: 'left',
    lineHeight: 20,
  },
  infoCard: {
    backgroundColor: '#3B3944',
    borderRadius: 20,
    padding: 25,
    maxWidth: 450,
    width: '100%',
  },
  infoText: {
    color: '#FFFFFF',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 22,
  },
  tableContainer: {
    width: '100%',
    maxWidth: 350,
    marginTop: 30,
    borderRadius: 10,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#4CAF50',
    paddingVertical: 12,
  },
  tableHeaderText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: '#3B3944',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  tableRowLast: {
    flexDirection: 'row',
    backgroundColor: '#3B3944',
    paddingVertical: 12,
  },
  tableCell: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 15,
    textAlign: 'center',
  },
  testimonialCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: 20,
    padding: 20,
    maxWidth: 400,
    width: '100%',
    marginBottom: 20,
  },
  testimonialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  avatarOrange: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FF9800',
  },
  avatarYellow: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFC107',
  },
  testimonialContent: {
    flex: 1,
  },
  testimonialText: {
    color: '#333333',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
    fontStyle: 'italic',
  },
  testimonialAuthor: {
    color: '#666666',
    fontSize: 13,
    fontWeight: '600',
  },
  ctaSection: {
    paddingHorizontal: 20,
    paddingVertical: 40,
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  ctaTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000000',
    textAlign: 'center',
    marginBottom: 10,
  },
  ctaSubtitle: {
    fontSize: 15,
    color: '#666666',
    textAlign: 'center',
    marginBottom: 25,
    paddingHorizontal: 20,
    maxWidth: 400,
  },
  ctaButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 40,
  },
  ctaButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  locationCard: {
    backgroundColor: '#4CAF50',
    borderRadius: 20,
    padding: 25,
    maxWidth: 400,
    width: '100%',
    alignItems: 'center',
  },
  locationTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 10,
  },
  locationSubtitle: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  featureCard: {
    backgroundColor: '#E8F5E9',
    borderRadius: 15,
    padding: 20,
    maxWidth: 400,
    width: '100%',
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  featureIcon: {
    fontSize: 32,
  },
  featureText: {
    flex: 1,
    color: '#333333',
    fontSize: 15,
    lineHeight: 22,
  },
  optionsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 15,
    justifyContent: 'center',
    marginTop: 10,
  },
  optionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    width: 160,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  optionIcon: {
    fontSize: 40,
    marginBottom: 10,
  },
  optionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333333',
    marginBottom: 5,
    textAlign: 'center',
  },
  optionDescription: {
    fontSize: 13,
    color: '#666666',
    textAlign: 'center',
  },
  footer: {
    backgroundColor: '#2C2C2E',
    paddingVertical: 40,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  footerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#4CAF50',
    marginBottom: 5,
  },
  footerSubtitle: {
    fontSize: 14,
    color: '#CCCCCC',
    marginBottom: 20,
  },
  footerLinks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    marginBottom: 20,
    justifyContent: 'center',
  },
  footerLink: {
    color: '#FFFFFF',
    fontSize: 14,
  },
  footerCopyright: {
    color: '#999999',
    fontSize: 12,
  },
});